[package]
name = "z4-bevy"
version = "0.1.0"
edition = "2021"

[features]
default = ["ws"]
ws = ["tdn-bevy/ws"]
p2p = ["tdn-bevy/p2p"]
wasm = ["tdn-bevy/wasm"]

[dependencies]
bevy = { version = "0.12", default-features = false }
serde_json = "1.0"
tdn_types = { version = "0.10", default-features = false, features = ["multiple"] }
tdn-bevy = { version = "0.1", path = "../../cympletech/tdn-bevy", default-features = false }

[dev-dependencies]
bevy = "0.12"
